#include "SceneManager/HuaHuoScene.h"
#include "SceneManager/SceneManager.h"
#include "Export/Events/ScriptEventManager.h"
#include "HuaHuoEngine.h"
#include "Components/Transform/Transform.h"
#include "ObjectStore.h"
#include "Shapes/LineShape.h"
#include "Shapes/CircleShape.h"
#include "Shapes/RectangleShape.h"
#include "Shapes/ImageShape.h"
#include "Shapes/AudioShape.h"
#include "Shapes/ElementShape.h"
#include "Shapes/TextShape.h"
#include "Shapes/CurveShape.h"
#include "KeyFrames/ShapeFollowCurveFrameState.h"
#include "KeyFrames/CustomComponent.h"
#include "Shapes/MirrorShape.h"

#ifdef HUAHUO_EDITOR
#include "Editor/SceneInspector.h"
#include "Editor/SceneView.h"
#include "Editor/Utility/SceneRootTransformArray.h"
#endif
#include "glue.cpp"