[NoDelete]
interface ScriptEventHandler{

};

[NoDelete]
interface ScriptEventHandlerArgs{

};

[JSImplementation="ScriptEventHandler", NoDelete]
interface ScriptEventHandlerImpl{
    void ScriptEventHandlerImpl();
    void handleEvent(ScriptEventHandlerArgs args);
};

interface PersistentManager{
    static PersistentManager GetPersistentManager();
};

interface HuaHuoEngine {
    static HuaHuoEngine getInstance();
    static void InitEngine();
    void RegisterEvent(DOMString eventType, ScriptEventHandler handler);
    PersistentManager GetPersistentManager();
};