[NoDelete]
interface GameObject {
    [Const] DOMString GetName();
    Transform GetTransform();
};

interface HuaHuoScene {
    boolean IsEmpty();
};

interface SceneManager {
    HuaHuoScene GetActiveScene();
    HuaHuoScene CreateScene();
    boolean SetActiveScene(HuaHuoScene scene);
};

[NoDelete]
interface Transform {
    [Const] DOMString GetName();
    Transform GetParent();
    boolean SetParent(Transform parent);
};

[NoDelete]
interface ScriptEventHandler{

};

[NoDelete]
interface ScriptEventHandlerArgs{

};

[NoDelete]
interface TransformHierarchyEventArgs: ScriptEventHandlerArgs{
    Transform GetTransform();
    Transform GetOldParent();
    Transform GetNewParent();
};

[JSImplementation="ScriptEventHandler", NoDelete]
interface ScriptEventHandlerImpl{
    void ScriptEventHandlerImpl();
    void handleEvent(ScriptEventHandlerArgs args);
};

interface SceneRootTransformArray{
    void SceneRootTransformArray(HuaHuoScene scene);
    boolean MoveNext();
    Transform GetCurrentTransform();
};

interface HuaHuoEngine {
    static HuaHuoEngine getInstance();
    static void InitEngine();

    GameObject CreateGameObject(DOMString name);
    void RegisterEvent(DOMString eventType, ScriptEventHandler handler);

    SceneManager GetSceneManager();
};