/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package online.huahuo.backend.app;

import online.huahuo.backend.list.LinkedList;

import static online.huahuo.backend.utilities.StringUtils.join;
import static online.huahuo.backend.utilities.StringUtils.split;
import static online.huahuo.backend.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
