/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package online.huahuo.backend.app;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.domain.EntityScan;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;

@SpringBootApplication(scanBasePackages = "online.huahuo.backend.*")
@EntityScan("online.huahuo.backend.db")
@EnableJpaRepositories("online.huahuo.backend.db")
public class HuahuoApplication {

    public static void main(String[] args) {
        SpringApplication.run(HuahuoApplication.class, args);
    }

}

