///////////////////////////////////////////////////////////////////////////////////
// NOTICE: Do not change the existing strings (both order and content); always
// put new strings at last because they are serialized
//

// (identifier, string without quotes)
COMMON_STRING_ENTRY(AABB, AABB)
COMMON_STRING_ENTRY(AnimationClip, AnimationClip)
COMMON_STRING_ENTRY(AnimationCurve, AnimationCurve)
COMMON_STRING_ENTRY(AnimationState, AnimationState)
COMMON_STRING_ENTRY(Array, Array)
COMMON_STRING_ENTRY(Base, Base)
COMMON_STRING_ENTRY(BitField, BitField)
COMMON_STRING_ENTRY(bitset, bitset)
COMMON_STRING_ENTRY(bool, bool)
COMMON_STRING_ENTRY(char, char)
COMMON_STRING_ENTRY(ColorRGBA, ColorRGBA)
COMMON_STRING_ENTRY(Component, Component)
COMMON_STRING_ENTRY(data, data)
COMMON_STRING_ENTRY(deque, deque)
COMMON_STRING_ENTRY(double, double)
COMMON_STRING_ENTRY(dynamic_array, dynamic_array)
COMMON_STRING_ENTRY(FastPropertyName, FastPropertyName)
COMMON_STRING_ENTRY(first, first)
COMMON_STRING_ENTRY(float, float)
COMMON_STRING_ENTRY(Font, Font)
COMMON_STRING_ENTRY(GameObject, GameObject)
COMMON_STRING_ENTRY(Generic_Mono, Generic Mono)
COMMON_STRING_ENTRY(GradientNEW, GradientNEW)
COMMON_STRING_ENTRY(GUID, GUID)
COMMON_STRING_ENTRY(GUIStyle, GUIStyle)
COMMON_STRING_ENTRY(int, int)
COMMON_STRING_ENTRY(list, list)
COMMON_STRING_ENTRY(long_long, long long)
COMMON_STRING_ENTRY(map, map)
COMMON_STRING_ENTRY(Matrix4x4f, Matrix4x4f)
COMMON_STRING_ENTRY(MdFour, MdFour)
COMMON_STRING_ENTRY(MonoBehaviour, MonoBehaviour)
COMMON_STRING_ENTRY(MonoScript, MonoScript)
COMMON_STRING_ENTRY(m_ByteSize, m_ByteSize)
COMMON_STRING_ENTRY(m_Curve, m_Curve)
COMMON_STRING_ENTRY(m_EditorClassIdentifier, m_EditorClassIdentifier)
COMMON_STRING_ENTRY(m_EditorHideFlags, m_EditorHideFlags)
COMMON_STRING_ENTRY(m_Enabled, m_Enabled)
COMMON_STRING_ENTRY(m_ExtensionPtr, m_ExtensionPtr)
COMMON_STRING_ENTRY(m_GameObject, m_GameObject)
COMMON_STRING_ENTRY(m_Index, m_Index)
COMMON_STRING_ENTRY(m_IsArray, m_IsArray)
COMMON_STRING_ENTRY(m_IsStatic, m_IsStatic)
COMMON_STRING_ENTRY(m_MetaFlag, m_MetaFlag)
COMMON_STRING_ENTRY(m_Name, m_Name)
COMMON_STRING_ENTRY(m_ObjectHideFlags, m_ObjectHideFlags)
COMMON_STRING_ENTRY(m_PrefabInternal, m_PrefabInternal)
COMMON_STRING_ENTRY(m_PrefabParentObject, m_PrefabParentObject)
COMMON_STRING_ENTRY(m_Script, m_Script)
COMMON_STRING_ENTRY(m_StaticEditorFlags, m_StaticEditorFlags)
COMMON_STRING_ENTRY(m_Type, m_Type)
COMMON_STRING_ENTRY(m_Version, m_Version)
COMMON_STRING_ENTRY(Object, Object)
COMMON_STRING_ENTRY(pair, pair)
COMMON_STRING_ENTRY(PPtr_Component, PPtr<Component>)
COMMON_STRING_ENTRY(PPtr_GameObject, PPtr<GameObject>)
COMMON_STRING_ENTRY(PPtr_Material, PPtr<Material>)
COMMON_STRING_ENTRY(PPtr_MonoBehaviour, PPtr<MonoBehaviour>)
COMMON_STRING_ENTRY(PPtr_MonoScript, PPtr<MonoScript>)
COMMON_STRING_ENTRY(PPtr_Object, PPtr<Object>)
COMMON_STRING_ENTRY(PPtr_Prefab, PPtr<Prefab>)
COMMON_STRING_ENTRY(PPtr_Sprite, PPtr<Sprite>)
COMMON_STRING_ENTRY(PPtr_TextAsset, PPtr<TextAsset>)
COMMON_STRING_ENTRY(PPtr_Texture, PPtr<Texture>)
COMMON_STRING_ENTRY(PPtr_Texture2D, PPtr<Texture2D>)
COMMON_STRING_ENTRY(PPtr_Transform, PPtr<Transform>)
COMMON_STRING_ENTRY(Prefab, Prefab)
COMMON_STRING_ENTRY(Quaternionf, Quaternionf)
COMMON_STRING_ENTRY(Rectf, Rectf)
COMMON_STRING_ENTRY(RectInt, RectInt)
COMMON_STRING_ENTRY(RectOffset, RectOffset)
COMMON_STRING_ENTRY(second, second)
COMMON_STRING_ENTRY(set, set)
COMMON_STRING_ENTRY(short, short)
COMMON_STRING_ENTRY(size, size)
COMMON_STRING_ENTRY(SInt16, SInt16)
COMMON_STRING_ENTRY(SInt32, SInt32)
COMMON_STRING_ENTRY(SInt64, SInt64)
COMMON_STRING_ENTRY(SInt8, SInt8)
COMMON_STRING_ENTRY(staticvector, staticvector)
COMMON_STRING_ENTRY(string, string)
COMMON_STRING_ENTRY(TextAsset, TextAsset)
COMMON_STRING_ENTRY(TextMesh, TextMesh)
COMMON_STRING_ENTRY(Texture, Texture)
COMMON_STRING_ENTRY(Texture2D, Texture2D)
COMMON_STRING_ENTRY(Transform, Transform)
COMMON_STRING_ENTRY(TypelessData, TypelessData)
COMMON_STRING_ENTRY(UInt16, UInt16)
COMMON_STRING_ENTRY(UInt32, UInt32)
COMMON_STRING_ENTRY(UInt64, UInt64)
COMMON_STRING_ENTRY(UInt8, UInt8)
COMMON_STRING_ENTRY(unsigned_int, unsigned int)
COMMON_STRING_ENTRY(unsigned_long_long, unsigned long long)
COMMON_STRING_ENTRY(unsigned_short, unsigned short)
COMMON_STRING_ENTRY(vector, vector)
COMMON_STRING_ENTRY(Vector2f, Vector2f)
COMMON_STRING_ENTRY(Vector3f, Vector3f)
COMMON_STRING_ENTRY(Vector4f, Vector4f)
COMMON_STRING_ENTRY(m_ScriptingClassIdentifier, m_ScriptingClassIdentifier)
COMMON_STRING_ENTRY(Gradient, Gradient)
COMMON_STRING_ENTRY(TypePtr, Type*)
COMMON_STRING_ENTRY(int2_storage, int2_storage)
COMMON_STRING_ENTRY(int3_storage, int3_storage)
COMMON_STRING_ENTRY(BoundsInt, BoundsInt)
COMMON_STRING_ENTRY(m_CorrespondingSourceObject, m_CorrespondingSourceObject)
COMMON_STRING_ENTRY(m_PrefabInstance, m_PrefabInstance)
COMMON_STRING_ENTRY(m_PrefabAsset, m_PrefabAsset)
COMMON_STRING_ENTRY(FileSize, FileSize)
