[Prefix="HuaHuo::"]
interface ByteArray {
    octet getByte(long idx);
};

[Prefix="HuaHuo::"]
interface PersistentManager {
    static PersistentManager getInstance();
    ByteArray getBuffer();
    long getBufferSize();
};

