[Prefix="HuaHuo::"]
interface ByteArray {
    octet getByte(long idx);
};

[Prefix="HuaHuo::"]
interface HuaHuoEngine {
    static HuaHuoEngine getInstance();
    ByteArray getBuffer();
    long getBufferSize();
};

