interface ScriptableRenderContext{

};

[NoDelete]
interface RenderPipeline{
};

[NoDelete]
interface Camera{

};

[NoDelete]
interface RenderPipelineManager{
    RenderPipelineManager GetManager();
    void SetRenderPipeline(RenderPipeline renderPipeline);
};

[JSImplementation="RenderPipeline", NoDelete]
interface RenderPipelineImpl{
    void RenderPipelineImpl();
    void Render(ScriptableRenderContext context);
};

