[NoDelete]
interface GameObject {
    [Const] DOMString GetName();
};

interface HuaHuoScene {

};

interface SceneManager {
    HuaHuoScene GetActiveScene();
    HuaHuoScene CreateScene();
    boolean SetActiveScene(HuaHuoScene scene);
};

enum EventType {
    "OnHierarchyChange"
};

interface ScriptEventHandler{

};

[JSImplementation="ScriptEventHandler"]
interface ScriptEventHandlerImpl{
    void ScriptEventHandlerImpl();
    void handleEvent();
};

interface HuaHuoEngine {
    static HuaHuoEngine getInstance();
    static void InitEngine();

    GameObject CreateGameObject(DOMString name);
    void RegisterEvent(EventType eventType, ScriptEventHandler handler);

    SceneManager GetSceneManager();
};