[NoDelete]
interface GameObject {
    [Const] DOMString GetName();
};

interface HuaHuoEngine {
    static HuaHuoEngine getInstance();
    static void InitEngine();

    GameObject CreateGameObject(DOMString name);
};

interface HuaHuoScene {

};

interface SceneManager {
    static SceneManager GetSceneManager();
    HuaHuoScene GetActiveScene();
    HuaHuoScene CreateScene();
    boolean SetActiveScene([Ref]HuaHuoScene scene);
};