//
// Created by VincentZhang on 4/11/2022.
//

#ifndef PERSISTENTMANAGER_CLASSREGISTRATION_H
#define PERSISTENTMANAGER_CLASSREGISTRATION_H

void RegisterAllClasses();

#endif //PERSISTENTMANAGER_CLASSREGISTRATION_H
