//
// Created by VincentZhang on 4/11/2022.
//

#ifndef HUAHUOENGINE_CLASSREGISTRATION_H
#define HUAHUOENGINE_CLASSREGISTRATION_H

void RegisterAllClasses();

#endif //HUAHUOENGINE_CLASSREGISTRATION_H
