//
// Created by VincentZhang on 5/17/2022.
//

#ifndef HUAHUOENGINE_MANAGERCONTEXTLOADING_H
#define HUAHUOENGINE_MANAGERCONTEXTLOADING_H

void CreateMissingGlobalGameManagers();

#endif //HUAHUOENGINE_MANAGERCONTEXTLOADING_H
